/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package webApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testTrue() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
       assertTrue(App.arraySumEquality(array, 2,3,5));
     }
 
     @Test
     public void testFalse() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
       assertFalse(App.arraySumEquality(array, 3,4,5));
     }
 
     @Test
     public void testEmptyArray() {
       ArrayList<Integer> array = new ArrayList<>();
       assertFalse(App.arraySumEquality(array, 1,2,3));
     }
 
     @Test
     public void testNull() {
       assertFalse(App.arraySumEquality(null, 1, 2, 3));
     }

     @Test
     public void testNegative() {
       assertFalse(App.arraySumEquality(new ArrayList<>(Arrays.asList(-1, -2, -3, -4)), -3, -4, -5));
     }
 
}
